# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Hola"
  url = "#hola"
  weight = 2
  
[[main]]
  name = "Skills"
  url = "#skills"
  weight = 3

[[main]]
  name = "Popular Topics"
  url = "#tags"
  weight = 4

[[main]]
  name = "Mundo R"
  url = "#mundo_R"
  weight = 5

[[main]]
  name = "Proyectos"
  url = "#proyectos"
  weight = 6

[[main]]
  name = "Media"
  url = "#media"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.

[[main]]
  name = "Curriculum"
  url = "#CV"
  weight = 8



[[main]]
  name = "CV en espa√±ol"
  url = "media/gomezvargas_cv.html"
  weight = 10
  parent = "Curriculum"

[[main]]
  name = "English CV"
  url = "media/gomezvargas_cv_EN.html"
  weight = 11 
  parent = "Curriculum"
